### ISSUE TITLE
Snippets and Inserts don't work

### ISSUE THREAD

**Issue by Rick-Kirkham** [Microsoft/vscode-docs-authoring#13]
Nothing happens when I choose Snippets or Inserts. I don't get the UI steps what appear in your animated gif.

**Comment by jamarw** [comment]
Hi @Rick-Kirkham , can you send us to OS and VS Code version you're using so we can look into it?  Thanks

**Comment by jamarw** [comment]
Hi @Rick-Kirkham , one additional question.  When working in VS Code, is your workspace scoped to the root of your cloned repo?

**Comment by Rick-Kirkham** [comment]
Windows 10 
VSC 1.21.1
There's no repo, I just opened and MD file in VS Code.

**Comment by jamarw** [comment]
Thanks for the info Rick.  The insert functionality works at the workspace-level (the clone in this case).  Once VS Code is opened from the root of the clone it provides environment context to the extension which allows for recursion, link creation, etc.  It would be good for the extension to provide information to the user if insert commands are used on a single file instead of through a workspace.  I've tagged this as an enhancement for upcoming releases.

**Comment by jamarw** [comment]
Resolved in release 0.0.2.  Notification message has been updated and will appear in the lower right corner of the VS Code window by default.
