### ISSUE TITLE
Switch back to Markdig

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-docs-authoring#195]
Fixing the issues that preview service is good, but it might be better to stick with Markdig instead of Markdown-It since that is what the publishing platform uses (right now AFAIK)

**Comment by bharney0** [comment]
I really like this idea of switching to Markdig because thats the MD engine that the Open Publishing Build uses. However, due to the effort it would require for switching rather than using the built-in functionality that VS Code offers. We made the decision to leverage the existing functionality of VS Code markdown-it extensions. However maybe in the future it will be easier to make the switch.

**Comment by nschonni** [comment]
OK, but just to point out that this project did us the the Markdig renderer with .Net core before, and then switched to markdown-it. This issue was to reverse that change since markdown-it extensions are great, but not supported by docs.microsoft.com
