### ISSUE TITLE
[docs-yaml] Question about YAMLMime

### ISSUE THREAD

**Issue by williamjamir** [microsoft/vscode-docs-authoring#661]
I would like to know more about `YAMLMime`. 

The readme says that YAMLMime is used to identify the schema to validate, but the link to the config file doesn't exist, also the repository named `schemas` referenced on the readme doesn't exist `https://github.com/MicrosoftDocs/schemas`

Is this `YAMLMime` an internal project from Microsoft or a public project? Do you have any links to a repo/docs with more information about the project or the current stage of it? 

Will the scheme used for validation be a subset of YAML 1.2 or will the specification be complete?

**Comment by 928PJY** [comment]
@williamjamir The YAMLMime is a Microsoft internal term which is only supported in the Docs content repository. you can reference here for all the schemas: https://static.docs.com/ui/latest/schemas/schema_config.json.
Since those schemas are all defined for the specific purposes of Docs content, there is no plan to public those schemas to be a subset of YAML 1.2.
