### ISSUE TITLE
Why when onSave in my  prettier why this Extension warning only work in markdown file? 

### ISSUE THREAD

**Issue by RedNeutorn** [microsoft/vscode-docs-authoring#822]

**Comment by pmahend1** [comment]
Looks like its being fired by one of the metadata commands
For me it happens when I try to save a C# file.

Moreover the commands are sending telemetry data without explicit setting for telemetry within these extensions.

![image](https://user-images.githubusercontent.com/21352870/109373816-2614a900-787f-11eb-8ddf-74bb34c47d40.png)

**Comment by vallentin** [comment]
I experience the same annoying popup each time I save .rs and .json files.

**Comment by bharney0** [comment]
@RedNeutorn @pmahend1 @vallentin Thank you for reporting this issue. Sorry for the annoyance. I have a [PR](#830) open for this to resolve the problem. Should be merged today or tomorrow.

**Comment by bharney0** [comment]
Please download the latest version of docs-markdown 0.2.84 to no longer experience the popup. This issue has been fixed and deployed to the VSCode marketplace.
