### ISSUE TITLE
Running local validation on powershell repo automatically creates extra yml, toc, and json files.

### ISSUE THREAD

**Issue by batamig** [microsoft/vscode-docs-authoring#845]
Running a local validation using the docs-validation extension creates extra yml, toc, and json files.
Each md file in the repo gets duplicated as a yml file, and then there are extra toc files and a json file added in.
i've disabled the automatic validation runs to avoid this, but a manual validation run will also cause the same effect.

![image](https://user-images.githubusercontent.com/26892178/111278634-6f684500-8642-11eb-96e5-eeb0d3855a8b.png)

This only happens to me on this repo: https://github.com/Azure/azure-docs-powershell-aip/

**Comment by bharney0** [comment]
@batamig Thank you for reporting this issue. @928PJY Can you look into this issue? I believe this was reported by another user during demo fest?

**Comment by 928PJY** [comment]
Sorry for the late response, this is a known issue, for some reference repository(with customized tasks in the op config), we need to transform the source files into valid input firstly (normally YAML files), and since we receive several issue report from the end-user, we are going to disable the real-time validation once we detect the `Cusomized_tasks` exists in the config file. But as you mentioned, this can only resolve the problem for the real-time validation, for the manual validation, the issue still exists. 

@batamig why do you need to use local validation on the reference repository? that is out of our current scope, but if that is a real requirement from the end-user, we will consider supporting that.

**Comment by batamig** [comment]
Thanks @928PJY! 
While this is a reference repo, the content isn't generated automatically - I update it manually, just as I would other repos. So the local validation would be helpful here. 

On the other hand, it's not a business critical feature so I've turned off the extension when working with this repo. 

My main use case is that if it's not turned off, all these extra files are created and I need to be careful that I don't commit them. Before I learned how to disable the extension, I was forced to make updates either in the browser, or in a text editor (both of which don't give me the option to run acrolinx before pushing). I think that if this use case is out of scope, it'd be helpful to document the known issue + workaround, as I'm sure there are other content devs in the same situation.

**Comment by 928PJY** [comment]
@batamig For sure, we will definitely add this to the known issue with the workaround, thanks for reporting, and sorry for the inconvenience, it is great to hear that the local validation is helpful, any feedback will be welcome.
BTW, you can disable the real-time validation for now as a workaround in the `workspace` level instead of global level, which will create a `settings` file under the `${repositoryRoot}/.vscode/` folder, so when you working on other repositories, you can still enjoy the benefit of the real-time validation.

**Comment by batamig** [comment]
excellent! thanks for the tip. please add this to the guidance / instructions as well since this is super-helpful information.
