### ISSUE TITLE
extension is not working

### ISSUE THREAD

**Issue by funnycom** [Microsoft/vscode-docs-authoring#92]
Issue Type: <b>Bug</b>

1) install the docs-markdown extension (v 0.1.2)
2) press Alt+M then nothing is changed.
3) select the 'Docs:Markdown authoring menu' from Command Panel, then error message is popped.

![vscode-1](https://user-images.githubusercontent.com/5915404/43152038-67e1c290-8fa8-11e8-9682-2642d27b152d.png)
![vscode-2](https://user-images.githubusercontent.com/5915404/43152039-680a53f4-8fa8-11e8-8943-3ea47c84bc88.png)

Extension version: 0.1.2
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.89GB (20.94GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by jamarw** [comment]
Hi @funnycom , thanks for bringing this to our attention.  Are you still running into this issue?

**Comment by funnycom** [comment]
Thanks jamarw.
I deleted and reinstalled the docs-markdown extension, but I enconter the same issue.

**Comment by jamarw** [comment]
No worries @funnycom .  I think I see what the issue is.  The docs-markdown extension works on files with an .md (markdown) extension.  It looks like the file from the screenshot has not been saved as an .md so the extension did not activate.  However, there should be a friendlier error message that pops up. I'll look into that but in the meantime would you mind installing the latest version of the extension (0.1.3) and trying to run the commands on a .md file to see if you still encounter the issue?

Thanks for your help with this.

**Comment by funnycom** [comment]
Ah.... I understand what you saying.  I'm appreciate for your kindly helping.
